### ISSUE TITLE
Build depends on non existing MOD artifacts (alsalib) and does not work ATM

### ISSUE THREAD

**Issue by rominator1983** [moddevices/mod-live-usb#13]
me again.

it looks like the build is broken atm. I got the same message "The specified account is disabled" somewhere else when trying to download some MOD things. So I guess it's because of the bankruptcy and stuff.
I don't quite know if another URL can/should be used or if this is a special alsalib-source that has to be used here.

![image](https://user-images.githubusercontent.com/13437300/190126755-cff9bfda-51f0-4af2-be81-aaa9b101b098.png)

**Comment by falkTX** [comment]
Just need to update the plugin-builder, which already has a fix for this. Let me do that quicky..

**Comment by rominator1983** [comment]
just letting you know it's working for me. thx a lot
