### ISSUE TITLE
root password not documented

### ISSUE THREAD

**Issue by rominator1983** [moddevices/mod-live-usb#15]
I am having trouble getting my self built ISO up and running TTY1 ok but I do not get a graphical UI.
Thus I wanted to check a few things and logon to TTY1 (qemu or via USB).
I can of course change the password in the shadow file in my cloned repository but that did not do the trick so far and I do not know the password for root (or any user with su) for the released ISO if I wanted to compare what's wrong...

So I think the password would best belong into the README.md right?

**Comment by falkTX** [comment]
there is no root password. I tried to disable it but failed

**Comment by falkTX** [comment]
so just try changing the airootfs live usb files to enable pw-less login.
