### ISSUE TITLE
Desktop view?

### ISSUE THREAD

**Issue by vedranius** [moddevices/mod-live-usb#16]
Hi,
as I'd like to run MODEP as background "software" while using desktop mode, is it possible to do so?
So, to have an ability to browse web, write something in libreoffice and also record audio on the same machine via Audacity, similar to Patchbox OS...
Thanks!

**Comment by falkTX** [comment]
no, the live-usb is a 100% focused mode.
in earlier builds not even X11 was available, but it made more complex setup of dialogs quite tricky so a X11 server is in place now.

if you want to run it as desktop app kinda deal, build and run `./mod-os/start.sh` with "net" as sound interface, then fetch back audio via jack net tools (netmanager internal client stuff)
