### ISSUE TITLE
host-python-setuptools Segmentation fault

### ISSUE THREAD

**Issue by ktulhu2000** [moddevices/mod-live-usb#19]
Thank you for your work!
I spent more than month trying to make it running. There was a great journey-)  but now I see new commits so may be you are interesting in bringing project back to life?

Now while trying x86 platform we are getting this on toolchain build:
>>> host-python-setuptools 18.7.1 Building
........
/bin/bash: line 1: 631075 Segmentation fault

In previous version I've solved (almost) these issues:
- plugins fluidplug, crypt are not compiling with static version set (just removed)
- notes-lv2 ( no go for whatever reason)
- mod-live-rwdata had no exec file flags (we are getting black screen on boot)
- alsa dint work inside systems-nspawn container. says no soundcards found
- no target/usr/lib creation command (latest commit in mod-os)

**Comment by falkTX** [comment]
> In previous version I've solved (almost) these issues:

previous version of what?

the build issue due to segfault is happening on CI side as well, as seen in a recent build https://github.com/moddevices/mod-live-usb/actions/runs/5369506867/jobs/9741828521
but I do not know why yet, suggestions/contributions welcome

**Comment by ktulhu2000** [comment]
> previous version of what?

I meant before this year commits. There was toolchain based on ubuntu.
 
> the build issue due to segfault is happening on CI side as well, as seen in a recent build https://github.com/moddevices/mod-live-usb/actions/runs/5369506867/jobs/9741828521 but I do not know why yet, suggestions/contributions welcome

Not a real programmer. All I've done required much blood and pain -)

**Comment by falkTX** [comment]
right, ok. at least I will try to fix up things to get them working again.
but this project is never really a priority so it goes very slow

**Comment by falkTX** [comment]
Fixed in b83fc993f427ef3133713ad83f4a31325f91747a

there is another error happening, unrelated to this, will fix that on the next commit.

**Comment by falkTX** [comment]
forgot to close this ticket, doing that now
