### ISSUE TITLE
Is it posssible to build a certain plugin under mod-live-usb?

### ISSUE THREAD

**Issue by Inqb8tr-jp** [moddevices/mod-live-usb#21]
Hi.

Can I build a lv2 plugin with commands below under mod-live-usb like mod-plugin-builder?
```
./build x86_64 lsp-plugins-impulsantworten
```
I tried but it made $HOME/mod-workdir...

And regarding lsp-plugins, there's no lsp related plugins avaliable on mod-live-usb, though there are files under mod-pluguin-builder/plugins/packages.

**Comment by falkTX** [comment]
those are defined in the plugins subdir, within the Makefile

but in any case the plugins being shipped are meant to match what is being used on MOD units.

**Comment by Inqb8tr-jp** [comment]
OK. Thank you for your information.
I'll check the Makefile.
