### ISSUE TITLE
mod-live-usb can boot but no further.

### ISSUE THREAD

**Issue by Inqb8tr-jp** [moddevices/mod-live-usb#23]
Hello, 
I am trying to build an iso image.
After "make mod-os", "make plugins" and "make -C live-welcome", I have successfully built the iso image with "make iso".
I can boot, but the pedalboard screen does not appear and the logo keeps showing up.
I have tried building with Ubuntu and Debian with the same results.
Do I need to make any additional adjustments?
Since I can get into the terminal, do I have to manually start mod-os or something?

**Comment by falkTX** [comment]
no, things are just broken at the moment. even if you got the pedalboard to show up, then the audio services would fail to start.

best to use the ISO releases for now, or debug things in a VM to figure out possible points of failure.

**Comment by Inqb8tr-jp** [comment]
OK. I'll wait for the next release.
Thanks for your info.
